services:
  db:
    image: postgres:15-alpine
    container_name: vicinatus-db
    environment:
      - POSTGRES_DB=vicinatus
      - POSTGRES_USER=mohamed
      - POSTGRES_PASSWORD=vicinatus
    ports:
      - "5432:5432"
    volumes:
      - vicinatus_data:/var/lib/postgresql/data

volumes:
  vicinatus_data: