spring.application.name=vicinatus
spring.datasource.url=jdbc:postgresql://localhost:5432/vicinatus
spring.datasource.username=tu_usuario_postgres
spring.datasource.password=tu_contraseña
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
